[VL-62] Improve documentation
pagopa/pn-local-emulator pull request #30
Opened 2022-09-15 09:00 UTC by kin0992

Improve README by adding more information on how to run the project locally, both using Node and Docker.

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2022-09-15 09:01 UTC, kin0992 commented
A note on this PR: the repo name in the commands is still the _old_ one, with the `poc` suffix.

2022-09-15 09:58 UTC, datalek requested changes

2022-09-15 09:58 UTC, datalek commented on README.md
> +git@github.com:pagopa/pn-local-emulator-poc.git
```suggestion
git clone git@github.com:pagopa/pn-local-emulator-poc.git
```

2022-09-15 10:41 UTC, datalek approved these changes
Yo!

2022-09-15 11:09 UTC, gunzip reviewed
I'll try to be more concise since devs doesn't like reading too much. Some comments are self-explanatory so they can be deleted as well.

2022-09-15 11:09 UTC, gunzip commented on README.md
> +In case you want to use it, after installing it, you can run the following command to install the correct version of Node.js:
I'd replace this with "install nvm" with a link

2022-09-15 11:09 UTC, gunzip commented on README.md
> +```shell
```suggestion
```

2022-09-15 11:09 UTC, gunzip commented on README.md
> +Make sure that the path of `.node_version` is correct, because the example commands assumes you are in the repository folder.
```suggestion
```

2022-09-15 11:09 UTC, gunzip commented on README.md
> +Before running the project, you should install the dependencies using the following command:
```suggestion
```

2022-09-15 11:09 UTC, gunzip commented on README.md
> +```shell
```suggestion
```
```

2022-09-15 11:09 UTC, gunzip commented on README.md
>  # start the application
```suggestion
```
```

2022-09-15 11:09 UTC, gunzip commented on README.md
> +Another option is to run the container image availeble in the container registry.
```suggestion
Another option is to run the container image available in the container registry.
```

2022-09-15 11:09 UTC, gunzip commented on README.md
> +```
```suggestion
```shell
docker pull ghcr.io/pagopa/pn-local-emulator-poc:latest
```

2022-09-15 11:09 UTC, gunzip commented on README.md
> +```shell
```suggestion
```

2022-09-15 11:09 UTC, gunzip commented on README.md
> +## Examples
examples of... ?

2022-09-15 12:33 UTC, lordkada commented
Prerequisites are not needed if the image is pulled from the registry. I think we should make it clear.

2022-09-15 14:00 UTC, kin0992 commented
I've changed the documentation after the feedback. @lordkada do you think now it is clear enough that the prerequisites are not mandatory in case of pulling the image from the container registry?

2022-09-16 07:59 UTC, lordkada commented
@kin0992 yep, I think it is clear enough now. Thx!

2022-09-16 09:23 UTC, kin0992 commented
> A note on this PR: the repo name in the commands is still the _old_ one, with the `poc` suffix.
> Ref: [#28 (comment)](https://github.com/pagopa/pn-local-emulator/pull/28#discussion_r971680148)

The repository has been renamed to `pn-local-emulator`

2022-09-16 09:24 UTC, datalek approved these changes

2022-09-16 09:25 UTC, merged