[VL-93] Change check notification status endpoint
pagopa/pn-local-emulator pull request #38
Opened 2022-09-27 09:08 UTC by datalek

Before this commit, the check notification status endpoint always returned the notification in the WAITING state. After this commit, the endpoint returns the notification with a different state. The new returned status is based on how many times the endpoint was called.

#### How Has This Been Tested?

Unit tests and e2e tests

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-09-27 09:11 UTC, datalek commented
This PR has a connection to #37. We should update one of the two to incorporate the changes once one of them is merged

2022-09-27 10:36 UTC, gunzip commented
We use [dpulls](https://www.dpulls.com/) so you can write "Depends on #37" I guess.

2022-09-27 12:08 UTC, datalek commented
> We use [dpulls](https://www.dpulls.com/) so you can write "Depends on #37" I guess.

Nice! Depends on https://github.com/pagopa/pn-local-emulator/pull/37

2022-09-29 08:55 UTC, kin0992 requested changes

2022-09-29 08:55 UTC, kin0992 commented on src/domain/CheckNotificationStatusRepository.ts
> +export const getNewNotificationRequestStatusResponse = (
```suggestion
const getNewNotificationRequestStatusResponse = (
```
this method is only called on line 25

2022-09-29 08:55 UTC, kin0992 commented on src/domain/NewNotificationRepository.ts
> +export const getNotification = (record: NewNotificationRecord): O.Option<Notification> =>
```suggestion
const getNotification = (record: NewNotificationRecord): O.Option<Notification> =>
```
private method

2022-09-29 09:02 UTC, kin0992 approved these changes
🌳

2022-09-29 09:03 UTC, merged